name: Deploy to Production (terraform)

on:
  push:
    branches:
      - mainprod_strap

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: strapi_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Terraform Init
        working-directory: environments/mainprod_strap
        run: terraform init
        env:
          TF_LOG: DEBUG
        continue-on-error: true

      - name: Terraform Init - Debug Logs
        if: failure()
        run: cat environments/mainprod_strap/terraform.log

      - name: Terraform Plan
        working-directory: environments/mainprod_strap
        run: terraform plan -out=tfplan
        env:
          TF_LOG: DEBUG
        continue-on-error: true

      - name: Terraform Plan - Debug Logs
        if: failure()
        run: cat environments/mainprod_strap/terraform.log

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: environments/mainprod_strap/tfplan

      - name: Download Terraform plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: environments/mainprod_strap/

      - name: Terraform Apply
        working-directory: environments/mainprod_strap
        run: terraform apply -auto-approve tfplan
        env:
          TF_LOG: DEBUG
