name: Deploy to Production (with terraform)

on:
  push:
    branches:
      - mainprod_strap

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: vyank_prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #added
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: .github/strapi_env/prod_env/
        run: terraform init

      - name: Terraform Plan
        working-directory: .github/strapi_env/prod_env/
        run: terraform plan -out=tfplan
        env:
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Terraform Apply
        working-directory: .github/strapi_env/prod_env/
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
